config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :matchings, only: %i[index show] do
    member do
      patch 'accept'
      patch 'refuse'
    end
  end

  resources :chatrooms, only: %i[show create index] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :matching
end

app/models/matching.rb
class Matching < ApplicationRecord
  belongs_to :user
  has_one :chatroom

  validates :user_one_status, presence: true
  validates :user_two_status, presence: true

  def second_associated_user
    User.find(user_two_id)
  end

  def first_associated_user
    self.user
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  validates :content, presence: true
  validates :chatroom_id, presence: true
  validates :user_id, presence: true

  def sender?(a_user)
    user.id == a_user.id
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  INSTRUMENTS = ['Guitare', 'Piano', 'Basse', 'Voix', 'Sax', 'Batterie']
  EXPERIENCES = ['Débutant', 'Confirmé', 'Expert']
  STYLES = ["Rock'n'roll", "Blues", "Jazz", "Funk", "Rap", "Electro", "Pop", "Reggea", "Métal"]

  # after_create :create_raw_matchings

  has_many :matchings

  has_one_attached :photo

  validates :nickname, presence: true
  validates :instrument, presence: true
  validates :city, presence: true
  validates :bio, presence: true
  validates :experience, presence: true
  validates :style, presence: true
  validates :birth_date, presence: true

  def age
    (Date.today.strftime('%Y%m%d').to_i - birth_date.strftime('%Y%m%d').to_i) / 10_000
  end

  # def create_raw_matchings
  #   (User.where.not(id: self.id)).each do |user|
  #     Matching.create(user: self, user_two_id: user.id, user_one_status: "pending", user_two_status: "pending")
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :birth_date, :style, :experience, :bio, :instrument, :city, :nickname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :birth_date, :style, :experience, :bio, :instrument, :city, :nickname])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @matchings_with_user_ref = current_user.matchings.where(user_one_status: "accept", user_two_status: "accept")
    @matchings_with_other_user = Matching.where(user_two_id: current_user.id, user_one_status: "accept", user_two_status: "accept")
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:id)
  end
end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController
  def index
    @matchings = Matching.all
  end

  def status(matching)
    
  end

  def show
    @matching = Matching.find(params[:id])
  end

  private

  def matching_params
    params.require(:matching).permit(:id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "messages/message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/helpers/icon_helper.rb
module IconHelper
  INSTRUMENTS = {
     guitare: "guit.png",
     piano: "key.png",
     basse: "bass.png",
     voix: "mic.png",
     sax: "sax.png",
     batterie: "drum.png"
  }

  def user_instrument(user)

    image_tag(INSTRUMENTS[user.instrument.downcase.to_sym])
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/chatrooms/index.html.erb
<div class="headmessage">
  <h1> Messages </h1>
  <div class="backbtn333">
    <%= link_to matchings_path do %>
    <%= image_tag "backblack.png", alt: "back" %>
    <% end %>
  </div>
</div>

<div class="matchencours">
  <p>CONNEXIONS</p>
  <div class="flexy">
    <% @matchings_with_user_ref.each do |matching| %>
      <div class="flexlink">
        <%= link_to chatroom_path(matching.chatroom.id) do %>
          <div class="fleximg">
            <%= cl_image_tag User.find(matching.user_two_id).photo.key%>
          </div>
        <% end %>
      </div>
    <% end %>
    <% @matchings_with_other_user.each do |matching| %>
      <div class="flexlink">
        <%= link_to chatroom_path(matching.chatroom.id) do %>
          <div class="fleximg">
            <%= cl_image_tag User.find(matching.user_id).photo.key%>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="messagesencours">

  <p>MESSAGES</p>

    <% @matchings_with_user_ref.each do |matching| %>
      <div class="dialchat">
          <div class="dedede">
        <%= link_to chatroom_path(matching.chatroom.id) do %>
            <%= cl_image_tag User.find(matching.user_two_id).photo.key%>
            <strong><%= matching.second_associated_user.nickname.upcase %></strong>,
            <%= matching.second_associated_user.instrument.capitalize %>
            <%= matching.second_associated_user.city %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% @matchings_with_other_user.each do |matching| %>
      <div class="dialchat">
        <%= link_to chatroom_path(matching.chatroom.id) do %>
          <div>
            <%= cl_image_tag User.find(matching.user_id).photo.key%>
            <strong><%= matching.first_associated_user.nickname.upcase %></strong>, <%= matching.first_associated_user.instrument.capitalize %>,
            <%= matching.first_associated_user.city %>
          </div>
        <% end %>
      </div>
    <% end %>
</div>

app/views/chatrooms/show.html.erb
   <div class="backbtn333" id="backfr" >
    <%= link_to chatrooms_path do %>
    <%= image_tag "backblack.png", alt: "back" %>
    <% end %>
    </div>
<div class="container chatroom"
  data-controller="chatroom-subscription"

  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

  <div class="titlemessage"><%= cl_image_tag current_user.photo.key%> </div>
  <div data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
            <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>

  <div id="positionmsg">
    <%= simple_form_for [@chatroom, @message],
      html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
    %>
      <%= f.input :content, label: false, placeholder: "...", wrapper_html: {class: "flex-grow-1"} %>
      <%= f.submit "Envoyer", class: "mybtn44" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path("logo_index.png") %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/matchings/accept.html.erb
<h1>Matchings#accept</h1>
<p>Find me in app/views/matchings/accept.html.erb</p>

app/views/matchings/index.html.erb
<div class="bodyindex" data-controller="swipe">
  <div class="banner">
    <div class="small"><a href="users/edit"> <%= image_tag "reglage.png", alt: "le logo" %></a></div>
    <div class="biglogo"><a href="/">  <%= image_tag "logo.png", alt: "le logo" %> </a></div>
    <div class="small">
      <%= link_to chatrooms_path do %>
        <%= image_tag "message.png", alt: "le logo" %>
      <% end %>
    </div>

  </div>

  <div class="mycard">
    <div class="profiles">
      <% @matchings.each do |matching| %>
        <div class="profile">
          <%= link_to matching_path(matching) do %>
            <div class="profile__image" style="background-image:  url('<%= cl_image_path User.find(matching.user_two_id).photo.key%>')">
              <div class="profile__infos">
                <div class="profile__name">
                  <span class="profile__age">
                    <strong><%= matching.second_associated_user.nickname.upcase %>,</strong>
                     <%= matching.second_associated_user.experience %>
                     <p class="textop" >
                      <%= matching.second_associated_user.style %> <%= matching.second_associated_user.city %> <%= user_instrument(matching.second_associated_user)%>  </p>
                  </span>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      <% end %>
      <div class="bottombar">
        <%if @matchings.present?%>
          <div class="bottombar__button">
            <%= button_to refuse_matching_path(@matchings.last),
              method: :patch,
              data: { turbo: false, swipe_target: "refuseButton" } do %>
                <%= image_tag "croix.png", alt: "Le logo" %>
              <% end %>
          </div>
          <div class="bottombar__button">
            <%= button_to accept_matching_path(@matchings.last),
            method: :patch,
            data: {turbo: false, swipe_target: "acceptButton"} do %>
              <%= image_tag "coeur.png", alt: "Le logo" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matchings/refuse.html.erb
<h1>Matchings#refuse</h1>
<p>Find me in app/views/matchings/refuse.html.erb</p>

app/views/matchings/show.html.erb
      <div class="profiles">
        <div class="profile2">
          <div class="profile__image" style="background-image:  url('<%=cl_image_path @matching.second_associated_user.photo.key%>')">
                <div class="backbtn">
                  <%= link_to matchings_path do %>
                  <%= image_tag "back.png", alt: "back" %>
                  <% end %>
                </div>
              <div class="profile__infos">
                <div class="profile__name"><span class="profile__age"> <strong><%= @matching.second_associated_user.nickname.upcase %></strong> , <%= @matching.second_associated_user.age %> ans</span>
                <p class="textop">  <%= @matching.second_associated_user.city %>, <%= @matching.second_associated_user.instrument %>, <%= @matching.second_associated_user.style %> </p>
                </div>
              </div>
            </div>
        </div>
        <div class="biocontainer">
          <p><%= @matching.second_associated_user.bio.capitalize %>.</p>
        </div>


        <div class="bottombar2">
          <div class="bottombar__button">
            <a href="#"> <%= image_tag "croix.png", alt: "le logo" %></a>
          </div>
          <div class="bottombar__button">
            <a href="#"> <%= image_tag "coeur.png", alt: "le logo" %></a>
          </div>
        </div>
    </div>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.nickname %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="background1">

  <div class="content">
   <p id="textlog"><strong>ZTRUT</strong></p>
  <div class="img">
    <%= image_tag "logo.png", alt: "le logo" %>
  </div>

  <p>Trouve et discute avec des musiciens à coté de chez toi !!</p>


  <div class="boutons">
    <%= link_to "C'est parti", matchings_path , class: "mybtn" %>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-none">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>